// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23uKJyfMUYKxSeuRe_MBvKd5sgXq2vWg',
    appId: '1:907364787673:android:4c9fa9cbc236e594c525c8',
    messagingSenderId: '907364787673',
    projectId: 'ecommerce-f153a',
    storageBucket: 'ecommerce-f153a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAuHIGLE88zHyA79qxHDzKmNvliMNXszg',
    appId: '1:907364787673:ios:3a037ddb20bceb4bc525c8',
    messagingSenderId: '907364787673',
    projectId: 'ecommerce-f153a',
    storageBucket: 'ecommerce-f153a.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAuHIGLE88zHyA79qxHDzKmNvliMNXszg',
    appId: '1:907364787673:ios:3a037ddb20bceb4bc525c8',
    messagingSenderId: '907364787673',
    projectId: 'ecommerce-f153a',
    storageBucket: 'ecommerce-f153a.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfZeNATOmrWamAQajfbik-giWzjzZn44w',
    appId: '1:907364787673:web:115c41dcade61c07c525c8',
    messagingSenderId: '907364787673',
    projectId: 'ecommerce-f153a',
    authDomain: 'ecommerce-f153a.firebaseapp.com',
    storageBucket: 'ecommerce-f153a.appspot.com',
    measurementId: 'G-3GG4Q2GQ9V',
  );
}
